WITH SORTED_TABLE AS (
    SELECT ID, SIZE_OF_COLONY,
    NTILE(4) OVER(ORDER BY SIZE_OF_COLONY DESC) AS USE_TABLE
    FROM ECOLI_DATA
)

SELECT ID,
        (CASE
            WHEN USE_TABLE = 1 THEN 'CRITICAL'
            WHEN USE_TABLE = 2 THEN 'HIGH'
            WHEN USE_TABLE = 3 THEN 'MEDIUM'
            ELSE 'LOW' END) AS COLONY_NAME
FROM SORTED_TABLE
ORDER BY ID ASC;