SELECT ED.ID, ED.GENOTYPE, PARENT.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA AS ED
INNER JOIN ECOLI_DATA AS PARENT
ON ED.PARENT_ID = PARENT.ID
WHERE ED.GENOTYPE & PARENT.GENOTYPE = PARENT.GENOTYPE
ORDER BY ID ASC;