SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE SKILL_CODE & (SELECT SUM(SC.CODE)
                   FROM SKILLCODES AS SC
                   WHERE SC.NAME IN ('C#', 'Python'))
ORDER BY ID ASC;