-- 코드를 입력하세요
SELECT 
FP.CATEGORY, 
FP.PRICE AS MAX_PRICE,
FP.PRODUCT_NAME
FROM FOOD_PRODUCT AS FP
JOIN (
    SELECT
    CATEGORY,
    MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
) AS MaxPricePerCategory
ON FP.CATEGORY = MaxPricePerCategory.CATEGORY
AND FP.PRICE = MaxPricePerCategory.MAX_PRICE
GROUP BY CATEGORY
ORDER BY MAX_PRICE DESC;

